# Server configuration
server:
  address: ":8080"

# Log configuration
log_level: "development"

# Database configuration
database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "app_db"
  sslmode: "disable"

# Redis configuration
redis:
  address: "localhost:6379"
  password: ""
  db: 0